import { DEFAULT_MODEL } from "@core/constants";

export const defaultFileParsingAgent = {
  components: [
    {
      id: "CM6JHAW8TNQB",
      name: "APIEndpoint",
      outputs: [
        { name: "headers", color: "#3C89F9", index: 0, default: true },
        { name: "body", color: "#3C89F9", index: 1, default: true },
        { name: "query", color: "#3C89F9", index: 2, default: true },
        {
          name: "message",
          color: "#3C89F9",
          expression: "body.message",
          index: 3,
          default: false,
        },
        {
          name: "attachments",
          color: "#3C89F9",
          expression: "body.attachments",
          index: 4,
          default: false,
        },
      ],
      inputs: [
        {
          name: "message",
          type: "Any",
          friendlyInputType: "Text",
          coreInputType: "Any",
          color: "#F35063",
          optional: false,
          description: "User's query.",
          index: 0,
          default: false,
        },
        {
          name: "attachments",
          type: "Binary",
          friendlyInputType: "Text",
          coreInputType: "Binary",
          color: "#F35063",
          optional: false,
          description:
            "Files, images, and attachments to parse and answer questions about.",
          index: 1,
          default: false,
        },
      ],
      data: {
        method: "POST",
        endpoint: "process_attachment_fallback",
        description:
          "Use this endpoint to process user queries with attachments, if there is no other endpoint to process the attachments.",
        ai_exposed: true,
        summary: "",
        advancedModeEnabled: false,
      },
      top: "72.6576px",
      left: "539.408px",
      width: "",
      height: "",
      displayName: "APIEndpoint",
      title: "Agent Skill",
      aiTitle: "",
      description: "An API Endpoint with input parameters for your AI agent.",
    },
    {
      id: "CM6JHDY7QJR",
      name: "APIOutput",
      outputs: [{ name: "Output", color: "#3C89F9", index: 0, default: true }],
      inputs: [
        {
          name: "result",
          type: "Any",
          friendlyInputType: "",
          coreInputType: "Any",
          color: "#F35063",
          optional: false,
          index: 0,
          default: false,
        },
      ],
      data: { format: "minimal" },
      top: "131.801px",
      left: "1269.49px",
      width: "",
      height: "",
      displayName: "APIOutput",
      title: "APIOutput",
      aiTitle: "",
      description: "",
    },
    {
      id: "CM6QMI3IGUCK",
      name: "GenAILLM",
      outputs: [{ name: "Reply", color: "#3C89F9", index: 0, default: true }],
      inputs: [
        {
          name: "Input",
          type: "Any",
          friendlyInputType: "",
          coreInputType: "",
          color: "#F35063",
          optional: false,
          index: 0,
          default: false,
        },
        {
          name: "Attachment",
          type: "Binary",
          friendlyInputType: "",
          coreInputType: "",
          color: "#F35063",
          optional: true,
          index: 1,
          default: false,
        },
      ],
      data: {
        model: DEFAULT_MODEL,
        prompt:
          "Answer question the user's questions: {{Input}}\nUse the attachments for context if needed.",
        temperature: "1",
        maxTokens: "16384",
        topP: "1",
        topK: "0",
        frequencyPenalty: "0",
        presencePenalty: "0",
        passthrough: false,
        stopSequences: "",
        maxThinkingTokens: "816",
      },
      top: "34.9306px",
      left: "902.845px",
      width: "",
      height: "",
      displayName: "GenAI LLM",
      title: "Question Answering System",
      aiTitle: "Question Answering System",
      description:
        "Make a GenAI request to an AI model. Works with many input file types.",
    },
  ],
  connections: [
    {
      sourceId: "CM6JHAW8TNQB",
      sourceIndex: 3,
      targetId: "CM6QMI3IGUCK",
      targetIndex: 0,
    },
    {
      sourceId: "CM6JHAW8TNQB",
      sourceIndex: 4,
      targetId: "CM6QMI3IGUCK",
      targetIndex: 1,
    },
    {
      sourceId: "CM6QMI3IGUCK",
      sourceIndex: 0,
      targetId: "CM6JHDY7QJR",
      targetIndex: 0,
    },
  ],
};
